[variables]
# Force rebuild comment: v2
# Automatic variables handled by Railway
NIXPACKS_LARAVEL_NO_DIAGNOSE = "1"

[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["composer install --no-dev --no-interaction --prefer-dist", "npm ci"]

[phases.build]
cmds = ["npm run prod"]

[start]
cmd = "php artisan config:clear && php artisan cache:clear && php artisan storage:link && php artisan migrate:fresh --seed --force && php artisan config:cache && php artisan route:cache && php artisan view:cache && node /assets/scripts/prestart.mjs /assets/nginx.template.conf /nginx.conf && (php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf)"
